### ISSUE TITLE
links are not available

### ISSUE THREAD

**Issue by raultang** [hortonworks/hoya#21]
all release links return 404, eg :
http://dffeaef8882d088c28ff-185c1feb8a981dddd593a05bb55b67aa.r18.cf1.rackcdn.com/hoya-0.13.1-all.tar.gz

**Comment by joshelser** [comment]
Might you be more interested in the releases from http://slider.incubator.apache.org/downloads/? Work on hoya hasn't been happening for some time.

**Comment by steveloughran** [comment]
That is old code: I don't know if it works with current Hadoop versions.

As Josh notes, Slider can do all that Hoya did and more

-Steve

**Comment by raultang** [comment]
Ok, thanks, I will try with Slider.
